### ISSUE TITLE
setup.sh many errors

### ISSUE THREAD

**Issue by jeffyromney** [pmtischler/auvsi_suas_competition#4]
my first error was that the module command did not exist. I fixed that with the command:
     sudo gem install puppet-module
the second error was:

         "install" was called incorrectly. Call as "install MODULE_NAME_OR_FILE [OPTIONS]".

I fixed that by placing the -f in the command at the end instead of before the module name

The third Error I haven't found a solution to yet. That is the following:
     Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type apt::source at /home/jefferson/auvsi_suas_competition/setup/puppet_files/auvsi_suas/manifests/apt_sources.pp:13 on node jrom.cfl.rr.com

jrom is the computer name and obviously jefferson is the username.  I don't know if these errors are specific to my computer, but at least the first two seem to be bigger than just my computer. Especially the syntax error in the second.

**Comment by pmtischler** [comment]
Sorry I forgot to commit the changes to fix this awhile back. Thank you for reminding me. I have pushed those changes and updated any docs. Please let me know if this fixes the issue on your end.

**Comment by jeffyromney** [comment]
Still getting all the same errors. I uninstalled everything I did before and started from scratch, reinstalled puppet and then ran the new setup.sh. this is what I got as an error at the end.   

Error: Unknown Puppet subcommand 'module'
See 'puppet help' for help on available puppet subcommands
Error: Unknown Puppet subcommand 'module'
See 'puppet help' for help on available puppet subcommands
Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type apt::source at /home/jefferson/auvsi_suas_competition/setup/puppet_files/auvsi_suas/manifests/apt_sources.pp:13 on node jrom.cfl.rr.com

so i ran the command:

     sudo gem install puppet-module


and then ran the setup.sh again getting the error:

"install" was called incorrectly. Call as "install MODULE_NAME_OR_FILE [OPTIONS]".
"install" was called incorrectly. Call as "install MODULE_NAME_OR_FILE [OPTIONS]".
Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type apt::source at /home/jefferson/auvsi_suas_competition/setup/puppet_files/auvsi_suas/manifests/apt_sources.pp:13 on node jrom.cfl.rr.com

I then edited the setup.sh file moving the -f in the install commands to look like this:

     sudo puppet module install puppetlabs/stdlib -f 
     sudo puppet module install puppetlabs-apt -f

I then ran the script again and got the following:

Installed "puppetlabs-stdlib-4.5.1" into directory: stdlib
Installed "puppetlabs-apt-1.7.0" into directory: apt
Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type apt::source at /home/jefferson/auvsi_suas_competition/setup/puppet_files/auvsi_suas/manifests/apt_sources.pp:13 on node jrom.cfl.rr.com

So it appears the install is now working with the change to the setup.sh file

I did notice the changes in the setup.sh file (merged the init.sh and setup.sh and added the std-lib)  but all three errors are still there.  I was able to patch the first 2 as before, but I still can't get past the 3rd

**Comment by pmtischler** [comment]
Which OS are you using? Did you start from a clean system (e.g. right after installing OS)? What version of Vagrant / Puppet are you using? 

Please note that we only support Ubuntu 14.04 LTS, as mentioned in the Wiki.

I just executed this on my Ubuntu 14.04 desktop and it ran fine. I also executed it on a clean MV with Vagrant and it also executed successfully.

**Comment by pmtischler** [comment]
Also when I execute:

```
puppet help module install
```

I get:

```
USAGE: puppet module install [--force | -f]
[--target-dir DIR | -i DIR]
[--ignore-dependencies]
[--version VER | -v VER]
<name>
```

Which would imply that my usage of `sudo puppet module install -f MODULE_NAME` is the correct format.

**Comment by jeffyromney** [comment]
Well i thought I was running the correct system but It turns out I was running 12.04.  don't know how I missed that but thanks!  I deleted my partition and started 100% fresh and it worked like a charm!

**Comment by pmtischler** [comment]
Awesome.
